[workspace]
authors = ["Betta_Fish <zxbmmmmmmmmm@outlook.com>"]
channels = ["conda-forge"]
name = "PattleCNN"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.5.3,<3"
pillow = ">=12.3.0,<13"
scikit-learn = ">=1.9.0,<2"
tqdm = ">=4.70.0,<5"
